<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:include filename="$(find hector_xacro_tools)/urdf/inertia_tensors.urdf.xacro" />
  <xacro:include filename="$(find hector_tracked_vehicles_description)/urdf/tracked_wheel.urdf.xacro" />
  
  <!-- Properties (Constants) -->
  <xacro:property name="M_PI" value="3.14159"/>

  <xacro:property name="base_link_size_x" value="0.397" />
  <xacro:property name="base_link_size_y" value="0.1789" /> <!--was 0.18-->
  <xacro:property name="base_link_size_z" value="${2*wheel_radius-ground_clearance}" /> <!-- old 0.102 is double radius without ground_clearance 0.07683 -->
  
  <xacro:property name="wheel_radius_big" value="0.1" /> <!--was 0.085--> <!--it's must be into file, but it isn't used-->
  
  <xacro:property name="wheel_offset_x" value="${base_link_size_x*0.5}" /> <!--del -0.42 -->
  <xacro:property name="wheel_offset_z" value="${-0.5*(2*wheel_radius-base_link_size_z)}" /> <!--was ${base_link_size_z*0.5-0.065 -0.012585 } -->  <!--it's difference between double radius and base-->
  <xacro:property name="wheel_radius"   value="0.051" /> <!--was 0.09-->
  
  <xacro:property name="track_width"    value="0.04" /> <!--old 0.1-->
  <xacro:property name="track_offset_y"    value="${(base_link_size_y-flipper_width)*0.5}" />  <!--old 0.155-->
  
  <xacro:property name="flipper_width"    value="0.028" />    <!--was 0.08-->
  <xacro:property name="flipper_offset_y"    value="${0.5*(base_link_size_y+*track_width)}" />  <!--old 0.245-->
  <xacro:property name="flipper_offset_wheel_axis_x"    value="0.355" /> <!--old 0.225 --> 
  
  <!-- I have added it-->
  <xacro:property name="flipper_offset_wheel_axis_z"    value="${wheel_offset_z}" /> <!--offset for enabled ground_clearance --> 
  <xacro:property name="small_flipper_wheel_radius"    value="0.02135" /> <!--offset for enabled ground_clearance old 0.0427/2-->
  <xacro:property name="track_thickness"    value="0.005" /> <!--offset for enabled ground_clearance old 0.0427/2-->   
  <!---->
  
  <xacro:property name="wheel_length" value="2" /> <!--i dont now how it can be used, old 0.02--> 
  <xacro:property name="wheel_size_y" value="2" /> <!--i dont now how it can be used, old 0.0825--> 
  
  <xacro:property name="total_width" value="2" /> <!--i dont now how it can be used, old 0.297--> 
  <!--    <xacro:property name="wheel_offset_y" value="${(total_width - wheel_size_y) / 2}" />-->
  <xacro:property name="wheel_offset_y" value="2" /> <!--i dont now how it can be used, old 0.1697--> 
  <xacro:property name="wheel_offset_z_from_base_link" value="2" />   <!--i dont now how it can be used, old -0.0--> 
  
  <xacro:property name="ground_clearance" value="0.02517" /> <!--old 0.05 0.02517-->
   
  <xacro:property name="top_size_x" value="${2*(base_link_size_x+flipper_offset_wheel_axis_x)}" />  <!--was 0.3937--> <!--i dont now how it can be used-->
  <xacro:property name="top_size_y" value="2" />  <!--was 0.3556--><!--i dont now how it can be used-->
  <xacro:property name="top_size_z" value="2" />  <!--was 0.0020--><!--i dont now how it can be used-->
  
  
  
  <!--
  Note macros below are exact copies of each with expection of the
  visual/collision tags.
  -->
  
  <xacro:macro name="track_geom_macro_visual" params="offset_y">
    <visual>
      <origin xyz="${wheel_offset_x} ${offset_y} ${wheel_offset_z}" rpy="${M_PI*0.5} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${track_width}" />
      </geometry>
    </visual>
    <visual>
      <origin xyz="${-wheel_offset_x} ${offset_y} ${wheel_offset_z}" rpy="${M_PI*0.5} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${track_width}" />
      </geometry>
    </visual>
    <visual>
      <origin xyz="0.0 ${offset_y} ${wheel_offset_z}" rpy="0 0 0" />
      <geometry>
        <box size="${base_link_size_x - wheel_radius} ${track_width} ${wheel_radius*2}" />
      </geometry>
    </visual>
  </xacro:macro>
  
  <xacro:macro name="track_geom_macro_collision" params="offset_y">
    <collision>
      <origin xyz="${wheel_offset_x} ${offset_y} ${wheel_offset_z}" rpy="${M_PI*0.5} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${track_width}" />
      </geometry>
    </collision>
    <collision>
      <origin xyz="${-wheel_offset_x} ${offset_y} ${wheel_offset_z}" rpy="${M_PI*0.5} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${track_width}" />
      </geometry>
    </collision>
    <collision>
      <origin xyz="0.0 ${offset_y} ${wheel_offset_z}" rpy="0 0 0" />
      <geometry>
        <box size="${base_link_size_x - wheel_radius} ${track_width} ${wheel_radius*2}" />
      </geometry>
    </collision>
  </xacro:macro>  
  
  <xacro:macro name="obelix_ugv_macro">
    
    <!-- Links and Joints (i.e., the robot) -->
    <link name="base_link">
      
      <xacro:inertial_cuboid_with_pose mass="40" x_length="${base_link_size_x}" y_length="${base_link_size_y}" z_length="${base_link_size_z}" >
        <origin xyz="0 0.0 0.0" rpy="0 0 0" />
      </xacro:inertial_cuboid_with_pose>
      
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <box size="${base_link_size_x} ${base_link_size_y} ${base_link_size_z}" />
        </geometry>
        <geometry>
          <box size="${base_link_size_x} ${base_link_size_y} ${base_link_size_z}" />
        </geometry>
        
        
        <material name="Grey" >
          <color rgba="0.8 0.8 0.8 1"/>
        </material>                
      </visual>
      
      <xacro:track_geom_macro_visual offset_y="${ track_offset_y}"/>
      <xacro:track_geom_macro_visual offset_y="${-track_offset_y}"/>        
      
      
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
          <box size="${base_link_size_x} ${base_link_size_y} ${base_link_size_z}" />
        </geometry>
        <geometry>
          <box size="${base_link_size_x} ${base_link_size_y} ${base_link_size_z}" />
        </geometry>            
      </collision>       
      
      <xacro:track_geom_macro_collision offset_y="${ track_offset_y}"/>
      <xacro:track_geom_macro_collision offset_y="${-track_offset_y}"/>
    </link>
    
  </xacro:macro>
</robot>
